### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "root",
  "password": "root"
}

> {%
    client.global.set("authToken", response.body.token);
  %}

### Browse all boats
GET http://localhost:8080/api/boats
Accept: application/hal+json
Authorization: Bearer {{authToken}}

### Register a new boat
POST http://localhost:8080/api/boats
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Tri-state Sailor",
  "description": "Behold, the evil vessel of tri-state area"
}
> {%
    client.global.set("boatId", response.body.id);
  %}

### Get the details of a particular boat
GET http://localhost:8080/api/boats/{{boatId}}
Accept: application/hal+json
Authorization: Bearer {{authToken}}

### Update boat info
PUT http://localhost:8080/api/boats
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "id": "{{boatId}}",
  "name": "Perry's bo-at",
  "description": "Was a bad bo-at, but now it is agent P's bo-at"
}

### Undock a boat
DELETE http://localhost:8080/api/boats/{{boatId}}
Accept: application/hal+json
Authorization: Bearer {{authToken}}
