logging:
  level:
    com:
      kata:
        boats: INFO

spring:
  application:
    name: BuoyancyOperatedAquaticTransportSociety

  docker:
    compose:
      file: src/main/docker/postgresql.yml
      lifecycle-management: start-only

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      poolName: Hikari
    url: jdbc:postgresql://localhost:5432/boats
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        generate_statistics: false
        jdbc:
          batch_size: 25
          time_zone: UTC
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - configprops
          - env
          - health
          - info
          - logfile
          - loggers
          - threaddump

server:
  port: 8080

application:
  security:
    oauth2:
      audience: account,api://default
