logging:
  level:
    com:
      kata:
        boats: DEBUG

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
