services:
  postgresql:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '127.0.0.1:5432:5432'
